version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    reviewers:
    - "dudustefanello"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
    - "dudustefanello"