# Generated by Django 5.1.1 on 2024-09-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_status_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
