# Generated by Django 5.1.1 on 2024-09-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('TENTATIVE', 'Tentativa'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='CONFIRMED', max_length=12),
        ),
    ]
