# Generated by Django 5.1.1 on 2024-09-19 14:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_recreate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencyrule',
            name='byweek',
        ),
        migrations.AddField(
            model_name='recurrencyrule',
            name='bymonthdate',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=83, null=True, verbose_name='data do mês'),
        ),
        migrations.AlterField(
            model_name='recurrencyrule',
            name='bymonthday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1SU', '1º Domingo'), ('1MO', '1ª Segunda'), ('1TU', '1ª Terça'), ('1WE', '1ª Quarta'), ('1TH', '1ª Quinta'), ('1FR', '1ª Sexta'), ('1SA', '1º Sábado'), ('2SU', '2º Domingo'), ('2MO', '2ª Segunda'), ('2TU', '2ª Terça'), ('2WE', '2ª Quarta'), ('2TH', '2ª Quinta'), ('2FR', '2ª Sexta'), ('2SA', '2º Sábado'), ('3SU', '3º Domingo'), ('3MO', '3ª Segunda'), ('3TU', '3ª Terça'), ('3WE', '3ª Quarta'), ('3TH', '3ª Quinta'), ('3FR', '3ª Sexta'), ('3SA', '3º Sábado'), ('4SU', '4º Domingo'), ('4MO', '4ª Segunda'), ('4TU', '4ª Terça'), ('4WE', '4ª Quarta'), ('4TH', '4ª Quinta'), ('4FR', '4ª Sexta'), ('4SA', '4º Sábado'), ('5SU', '5º Domingo'), ('5MO', '5ª Segunda'), ('5TU', '5ª Terça'), ('5WE', '5ª Quarta'), ('5TH', '5ª Quinta'), ('5FR', '5ª Sexta'), ('5SA', '5º Sábado'), ('1SU', 'Último Domingo'), ('1MO', 'Última Segunda'), ('1TU', 'Última Terça'), ('1WE', 'Última Quarta'), ('1TH', 'Última Quinta'), ('1FR', 'Última Sexta'), ('1SA', 'Último Sábado')], max_length=167, null=True, verbose_name='dia do mês'),
        ),
        migrations.AlterField(
            model_name='recurrencyrule',
            name='freq',
            field=models.CharField(choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal (data)'), ('MONTHDAY', 'Mensal (mês)'), ('YEARLY', 'Anual (data)'), ('YEARDAY', 'Anual (mês)')], default='DAILY', max_length=8, verbose_name='frequência'),
        ),
    ]
