name: TestPullRequest

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --extra-index-url https://${{ secrets.PYPI_URL_USERNAME }}:${{ secrets.PYPI_URL_PASSWORD }}@pip.stefanello.cc/simple/ .

    - name: Run coverage
      run: |
        pip install coverage
        coverage run runtests.py

    - name: Exports coverage
      run: |
        echo "<details><summary><h3>Resultado da cobertura de testes:</summary>" > coverage.md
        echo "" >> coverage.md
        echo "<pre><code>" >> coverage.md
        coverage report -m --skip-empty --skip-covered >> coverage.md
        echo "</code></pre></details>" >> coverage.md

    - name: Comment coverage results
      uses: thollander/actions-comment-pull-request@v2.5.0
      with:
        filePath: ./coverage.md
        comment_tag: coverage.md
